also record json output from install actions

diff --git a/scripts/opam-ci-install b/scripts/opam-ci-install
--- a/scripts/opam-ci-install
+++ b/scripts/opam-ci-install
@@ -7,10 +7,25 @@ cmd() {
 
 export OPAMERRLOGLEN=0
 export OPAMYES=1
+
+echo --- Installing external dependencies
 starttime=`date +%s`
-cmd opam depext -iyj 2 $1 > $1.txt 2>&1
+cmd opam depext -y $1 > $1.txt 2>&1
 exitcode=$?
 endtime=`date +%s`
+
+# as a special case, raise exit 51 for a depext failure
+if [ $exitcode -ne 0 ]; then
+  echo '{}' >> $1.txt
+  echo $exitcode $starttime $endtime >> $1.txt
+  exit 51
+fi
+
+echo --- Installing opam package
+cmd opam install --json $1.json -y -j 2 >> $1.txt 2>&1
+exitcode=$?
+endtime=`date +%s`
+cat $1.json >> $1.txt
 echo $exitcode $starttime $endtime >> $1.txt
 cat $1.txt
 exit 0
